<?php
$dbhost="localhost";
$dbuser="root";
$dbpassword="secret";
$dbname="aspirezsg_hrms";
$version="0.9d";
$pgport=5432;
//$picturepath="../simbiz/modules/simantz/upload/stock/item";
$url = "../application";
$tbprefix="ins";
$slogan="Human Resourse System";
$title="Welcome to Human Resourse System";
$iconpath="images";
$smtpuser="sl5310520@hotmail.com";
$sltType="Color";
$password_md5_option="ON";
$mandatorysign="<b style='color:red'>*</b>";
$upload_path = "C:/Server/WebDocs/aspirez_hrms/application/upload";
$up_path = "../upload";
$employee_logo = "employee-icon.jpg";
?>